version: '3.8'
services: 
  database:
    build: ../database/
    # Variáveis de ambiente obtidas do arquivo .env, a serem passadas ao container
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:5432"
    networks:
      - backend-network
  
  backend:
    build: ../backend/
    # Variáveis de ambiente obtidas do arquivo .env, a serem passadas ao container
    environment:
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "$PORT:8080"
    networks:
      - backend-network
    depends_on:
      - database

networks:
  backend-network:
    driver: bridge
